### ISSUE TITLE
Gulp + PostCSS tooling setup

### ISSUE THREAD

**Issue by bdenham** [benfrain/ecss#2]
Do you have a seed project somewhere so I can see all the details and actually run the tooling setup? I've read your book and have seen the partial gulpfile and style lint config you listed there, but I need to the whole enchilada if you can point me there.

Thanks,
Bruce

**Comment by benfrain** [comment]
Hi Bruce, take a look here: https://github.com/benfrain/ecss-postcss-shell

**Comment by bdenham** [comment]
Perfect. Thank you!
