### ISSUE TITLE
ECSS + ITCSS?

### ISSUE THREAD

**Issue by corysimmons** [benfrain/ecss#3]
I kinda like parts of Harry's ITCSS organization:

https://www.youtube.com/watch?v=1OKZOV-iLj4

![image](https://cloud.githubusercontent.com/assets/224636/14359517/b9c033b8-fcbf-11e5-83ed-21bcc2358d71.png)

I can see how the atomic layers could be tricky with ECSS, but what are your thoughts on some of the more generic layers?

**Comment by benfrain** [comment]
Hi Cory,

Nothing generic from my POV. The whole point of ECSS is everything is isolated and self contained. 

:)

**Comment by corysimmons** [comment]
Not even base styles for things like typography?

I see it as a reset.

`:root { color: orange; }` is legit right?

**Comment by benfrain** [comment]
Yes, some stuff like that is unavoidable but I stay away from any kind of 'utility' styles or grid classes. 

Essentially, with ECSS any class based abstractions are considered 'leaky' and therefore avoided :)

**Comment by corysimmons** [comment]
Alright sounds good. :+1:
