### ISSUE TITLE
ECSS slides as a presentation?

### ISSUE THREAD

**Issue by corysimmons** [benfrain/ecss#4]
Happen to have http://ecss.io/slides1 available as a video presentation?

**Comment by benfrain** [comment]
Sorry, no. It was supposed to be filmed when I presented it at McrFRED last year but the video folk didn't show. Hopefully be presenting it again soon so will hopefully get a decent recording then. 

Thanks for the interest!

**Comment by corysimmons** [comment]
Not a problem. Thanks
