### ISSUE TITLE
ECSS and em units

### ISSUE THREAD

**Issue by juliami** [benfrain/ecss#7]
Hi Ben,

First - thanks your for your amazing work. The advantages of ECSS cannot be stressed enough.

I was wondering what's your approach towards the relative units like _em_. They are inheritance dependent, so should they be used in the modular architecture?

Regards,
Julia

**Comment by benfrain** [comment]
Hi, thanks for the kind words and glad ECSS is proving useful. 👍 

I think ems are fine for modular work as long as the root of your component is set in a non compounding length unit e.g. rem/px.  

In practice this just means using rem or px at the root of your component and then use em within if it suits your needs.

Two good reads on approaches similar to this:

http://simurai.com/blog/2013/07/03/sizing-components
https://css-tricks.com/rems-ems/

However, I also make the argument in some circumstances for just using pixels ;)

https://benfrain.com/just-use-pixels/

**Comment by benfrain** [comment]
Hi @juliami I'm closing this one down. If you have any further queries on this feel free to comment and I can open back up 👍
